//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASESORIA
    {
        public int ID_ASESORIA { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_PLAN_MEJORAS { get; set; }
    
        public virtual PLAN_MEJORAS PLAN_MEJORAS { get; set; }
    }
}
