//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public int ID_CAPACITACION { get; set; }
        public System.DateTime FECHA { get; set; }
        public string HORA { get; set; }
        public int ID_PARTICIPANTE_CAPACITACION { get; set; }
        public int ID_MATERIALES_CAPACITACION { get; set; }
    
        public virtual MATERIALES_EN_CAPACITACION MATERIALES_EN_CAPACITACION { get; set; }
        public virtual PARTICIPANTE_CAPACITACION PARTICIPANTE_CAPACITACION { get; set; }
    }
}
