//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASOS
    {
        public int ID_CASOS { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_CASO { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public string RESOLUCION { get; set; }
        public int ID_TIPO_CASO { get; set; }
        public int ID_ESTADO_CASO { get; set; }
        public int RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_CASO ESTADO_CASO { get; set; }
        public virtual TIPO_CASO TIPO_CASO { get; set; }
    }
}
