//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.ALERTA_ACCIDENTE = new HashSet<ALERTA_ACCIDENTE>();
            this.CASOS = new HashSet<CASOS>();
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
            this.INFORME = new HashSet<INFORME>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.PLANILLA = new HashSet<PLANILLA>();
            this.REGISTRO_ACTIVIDADES = new HashSet<REGISTRO_ACTIVIDADES>();
        }
    
        public int RUT_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual ICollection<ALERTA_ACCIDENTE> ALERTA_ACCIDENTE { get; set; }
        public virtual ICollection<CASOS> CASOS { get; set; }
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
        public virtual ICollection<INFORME> INFORME { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual ICollection<PLANILLA> PLANILLA { get; set; }
        public virtual ICollection<REGISTRO_ACTIVIDADES> REGISTRO_ACTIVIDADES { get; set; }
    }
}
