//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES_DOCUMENTOS
    {
        public DETALLES_DOCUMENTOS()
        {
            this.SERVICIOS = new HashSet<SERVICIOS>();
        }
    
        public int ID_DETALLES_DOCUMENTOS { get; set; }
        public string DESCRIPCION { get; set; }
        public int VALOR_COBRADO { get; set; }
        public int ID_DOCUMENTOS { get; set; }
    
        public virtual DOCUMENTOS DOCUMENTOS { get; set; }
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
    }
}
