//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALERTA_ACCIDENTE> ALERTA_ACCIDENTE { get; set; }
        public DbSet<ALERTA_PROXIMO_PAGO> ALERTA_PROXIMO_PAGO { get; set; }
        public DbSet<ASESORIA> ASESORIA { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CASOS> CASOS { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<DETALLE_ACCIDENTE> DETALLE_ACCIDENTE { get; set; }
        public DbSet<DETALLES_DOCUMENTOS> DETALLES_DOCUMENTOS { get; set; }
        public DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public DbSet<ESTADO_CASO> ESTADO_CASO { get; set; }
        public DbSet<ESTADO_INFORME> ESTADO_INFORME { get; set; }
        public DbSet<ESTADO_SOLICITUDES> ESTADO_SOLICITUDES { get; set; }
        public DbSet<ESTADO_USUARIOS> ESTADO_USUARIOS { get; set; }
        public DbSet<INFORME> INFORME { get; set; }
        public DbSet<LISTA> LISTA { get; set; }
        public DbSet<MATERIALES> MATERIALES { get; set; }
        public DbSet<MATERIALES_EN_CAPACITACION> MATERIALES_EN_CAPACITACION { get; set; }
        public DbSet<MEJORAS> MEJORAS { get; set; }
        public DbSet<METODOS_PAGOS> METODOS_PAGOS { get; set; }
        public DbSet<MOROSIDAD> MOROSIDAD { get; set; }
        public DbSet<PAGOS> PAGOS { get; set; }
        public DbSet<PARTICIPANTE_CAPACITACION> PARTICIPANTE_CAPACITACION { get; set; }
        public DbSet<PARTICIPANTES> PARTICIPANTES { get; set; }
        public DbSet<PLAN_MEJORAS> PLAN_MEJORAS { get; set; }
        public DbSet<PLANILLA> PLANILLA { get; set; }
        public DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public DbSet<REGISTRO_ACCIDENTES> REGISTRO_ACCIDENTES { get; set; }
        public DbSet<REGISTRO_ACTIVIDADES> REGISTRO_ACTIVIDADES { get; set; }
        public DbSet<ROLES_USUARIOS> ROLES_USUARIOS { get; set; }
        public DbSet<SERVICIOS> SERVICIOS { get; set; }
        public DbSet<SERVICIOS_EN_CONTRATOS> SERVICIOS_EN_CONTRATOS { get; set; }
        public DbSet<SOLICITUDES> SOLICITUDES { get; set; }
        public DbSet<TIPO_CASO> TIPO_CASO { get; set; }
        public DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public DbSet<TIPO_SOLICITUDES> TIPO_SOLICITUDES { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITA> VISITA { get; set; }
    
        public virtual int SPP_CREAR_INFORME(string dESCRIPCION, Nullable<decimal> iDESTADO, Nullable<decimal> rUTPROF, Nullable<decimal> rUTCLIENTE, Nullable<decimal> iDPLANILLA)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            var rUTPROFParameter = rUTPROF.HasValue ?
                new ObjectParameter("RUTPROF", rUTPROF) :
                new ObjectParameter("RUTPROF", typeof(decimal));
    
            var rUTCLIENTEParameter = rUTCLIENTE.HasValue ?
                new ObjectParameter("RUTCLIENTE", rUTCLIENTE) :
                new ObjectParameter("RUTCLIENTE", typeof(decimal));
    
            var iDPLANILLAParameter = iDPLANILLA.HasValue ?
                new ObjectParameter("IDPLANILLA", iDPLANILLA) :
                new ObjectParameter("IDPLANILLA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_CREAR_INFORME", dESCRIPCIONParameter, iDESTADOParameter, rUTPROFParameter, rUTCLIENTEParameter, iDPLANILLAParameter);
        }
    
        public virtual int SPP_CREAR_PLANILLA(string dESCRIPCION, Nullable<decimal> rUTCLIENTE)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var rUTCLIENTEParameter = rUTCLIENTE.HasValue ?
                new ObjectParameter("RUTCLIENTE", rUTCLIENTE) :
                new ObjectParameter("RUTCLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_CREAR_PLANILLA", dESCRIPCIONParameter, rUTCLIENTEParameter);
        }
    
        public virtual int SPP_ELIMINAR_PLANILLA(Nullable<decimal> iDE)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_ELIMINAR_PLANILLA", iDEParameter);
        }
    
        public virtual int SPP_ELIMINARREGISTRO(Nullable<decimal> iDE)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_ELIMINARREGISTRO", iDEParameter);
        }
    
        public virtual int SPP_ELIMINARUSUARIO(Nullable<decimal> iDE)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_ELIMINARUSUARIO", iDEParameter);
        }
    
        public virtual int SPP_INSERTARCLIENTE(string rUT, string nOMBRE, string rUBRO, string cORREO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var rUBROParameter = rUBRO != null ?
                new ObjectParameter("RUBRO", rUBRO) :
                new ObjectParameter("RUBRO", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_INSERTARCLIENTE", rUTParameter, nOMBREParameter, rUBROParameter, cORREOParameter);
        }
    
        public virtual int SPP_INSERTARPROF(string rUT, string nOMBRE, Nullable<decimal> rOL)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var rOLParameter = rOL.HasValue ?
                new ObjectParameter("ROL", rOL) :
                new ObjectParameter("ROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_INSERTARPROF", rUTParameter, nOMBREParameter, rOLParameter);
        }
    
        public virtual int SPP_INSERTARSOLI(Nullable<decimal> rUT, Nullable<decimal> tIPOS, Nullable<System.DateTime> fECHA)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var tIPOSParameter = tIPOS.HasValue ?
                new ObjectParameter("TIPOS", tIPOS) :
                new ObjectParameter("TIPOS", typeof(decimal));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_INSERTARSOLI", rUTParameter, tIPOSParameter, fECHAParameter);
        }
    
        public virtual int SPP_INSERTARUSUARIO(string nOMBRE, string cONTRASENAU, Nullable<decimal> iD_ROL)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cONTRASENAUParameter = cONTRASENAU != null ?
                new ObjectParameter("CONTRASENAU", cONTRASENAU) :
                new ObjectParameter("CONTRASENAU", typeof(string));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_INSERTARUSUARIO", nOMBREParameter, cONTRASENAUParameter, iD_ROLParameter);
        }
    
        public virtual int SPP_LISTAR_CLIENT(string bUS)
        {
            var bUSParameter = bUS != null ?
                new ObjectParameter("BUS", bUS) :
                new ObjectParameter("BUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_CLIENT", bUSParameter);
        }
    
        public virtual int SPP_LISTAR_INFORMES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_INFORMES");
        }
    
        public virtual int SPP_LISTAR_LISTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_LISTA");
        }
    
        public virtual int SPP_LISTAR_PAGOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_PAGOS");
        }
    
        public virtual int SPP_LISTAR_PROFESIONALES(string bUS)
        {
            var bUSParameter = bUS != null ?
                new ObjectParameter("BUS", bUS) :
                new ObjectParameter("BUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_PROFESIONALES", bUSParameter);
        }
    
        public virtual int SPP_LISTAR_SOLICITUDES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_SOLICITUDES");
        }
    
        public virtual int SPP_LISTAR_USUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_LISTAR_USUARIOS");
        }
    
        public virtual int SPP_MODIFICAR_INFORME(Nullable<decimal> iDE, string dESCRIPCION, Nullable<decimal> iDESTADO, Nullable<decimal> rUTPROF, Nullable<decimal> rUTCLIENTE, Nullable<decimal> iDPLANILLA)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            var rUTPROFParameter = rUTPROF.HasValue ?
                new ObjectParameter("RUTPROF", rUTPROF) :
                new ObjectParameter("RUTPROF", typeof(decimal));
    
            var rUTCLIENTEParameter = rUTCLIENTE.HasValue ?
                new ObjectParameter("RUTCLIENTE", rUTCLIENTE) :
                new ObjectParameter("RUTCLIENTE", typeof(decimal));
    
            var iDPLANILLAParameter = iDPLANILLA.HasValue ?
                new ObjectParameter("IDPLANILLA", iDPLANILLA) :
                new ObjectParameter("IDPLANILLA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_MODIFICAR_INFORME", iDEParameter, dESCRIPCIONParameter, iDESTADOParameter, rUTPROFParameter, rUTCLIENTEParameter, iDPLANILLAParameter);
        }
    
        public virtual int SPP_MODIFICAR_PLANILLA(Nullable<decimal> iDE, string dESCRIPCION, Nullable<decimal> rUTCLIENTE)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var rUTCLIENTEParameter = rUTCLIENTE.HasValue ?
                new ObjectParameter("RUTCLIENTE", rUTCLIENTE) :
                new ObjectParameter("RUTCLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_MODIFICAR_PLANILLA", iDEParameter, dESCRIPCIONParameter, rUTCLIENTEParameter);
        }
    
        public virtual int SPP_MODIFICARREGISTROR(Nullable<decimal> iDE, Nullable<decimal> rUT)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_MODIFICARREGISTROR", iDEParameter, rUTParameter);
        }
    
        public virtual int SPP_MODIFICARSOLIRE(Nullable<decimal> iDE, Nullable<System.DateTime> fECHACIERRE, string rESOLUTION, Nullable<decimal> iD_ESTADO)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            var fECHACIERREParameter = fECHACIERRE.HasValue ?
                new ObjectParameter("FECHACIERRE", fECHACIERRE) :
                new ObjectParameter("FECHACIERRE", typeof(System.DateTime));
    
            var rESOLUTIONParameter = rESOLUTION != null ?
                new ObjectParameter("RESOLUTION", rESOLUTION) :
                new ObjectParameter("RESOLUTION", typeof(string));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_MODIFICARSOLIRE", iDEParameter, fECHACIERREParameter, rESOLUTIONParameter, iD_ESTADOParameter);
        }
    
        public virtual int SPP_MODIFICARUSR(Nullable<decimal> iDE, string nOMBRE, string cONTRASENAU, Nullable<decimal> iD_ROL, Nullable<decimal> iD_ESTADO)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cONTRASENAUParameter = cONTRASENAU != null ?
                new ObjectParameter("CONTRASENAU", cONTRASENAU) :
                new ObjectParameter("CONTRASENAU", typeof(string));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(decimal));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_MODIFICARUSR", iDEParameter, nOMBREParameter, cONTRASENAUParameter, iD_ROLParameter, iD_ESTADOParameter);
        }
    
        public virtual int SPP_MODIFICARUSUARIO(Nullable<decimal> iDE, string nOMBRE, Nullable<decimal> cONTRASENAU, Nullable<decimal> iD_ROL, Nullable<decimal> iD_ESTADO)
        {
            var iDEParameter = iDE.HasValue ?
                new ObjectParameter("IDE", iDE) :
                new ObjectParameter("IDE", typeof(decimal));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cONTRASENAUParameter = cONTRASENAU.HasValue ?
                new ObjectParameter("CONTRASENAU", cONTRASENAU) :
                new ObjectParameter("CONTRASENAU", typeof(decimal));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(decimal));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPP_MODIFICARUSUARIO", iDEParameter, nOMBREParameter, cONTRASENAUParameter, iD_ROLParameter, iD_ESTADOParameter);
        }
    }
}
