//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME
    {
        public int ID_INFORME { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_ESTADO_INFO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int RUT_PROFESIONAL { get; set; }
        public int RUT_CLIENTE { get; set; }
        public int ID_PLANILLA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_INFORME ESTADO_INFORME { get; set; }
        public virtual PLANILLA PLANILLA { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
    }
}
