//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class METODOS_PAGOS
    {
        public METODOS_PAGOS()
        {
            this.PAGOS = new HashSet<PAGOS>();
        }
    
        public int ID_METODOS_PAGOS { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<PAGOS> PAGOS { get; set; }
    }
}
