//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public PAGOS()
        {
            this.DOCUMENTOS = new HashSet<DOCUMENTOS>();
        }
    
        public int ID_PAGOS { get; set; }
        public short CUOTA { get; set; }
        public int MONTO_CUOTA { get; set; }
        public int ID_ALERTA_PROXIMO_PAGO { get; set; }
        public int ID_METODOS_PAGOS { get; set; }
    
        public virtual ALERTA_PROXIMO_PAGO ALERTA_PROXIMO_PAGO { get; set; }
        public virtual ICollection<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual METODOS_PAGOS METODOS_PAGOS { get; set; }
    }
}
