//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_MEJORAS
    {
        public PLAN_MEJORAS()
        {
            this.ASESORIA = new HashSet<ASESORIA>();
        }
    
        public int ID_PLAN_MEJORAS { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_MEJORAS { get; set; }
    
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
        public virtual MEJORAS MEJORAS { get; set; }
    }
}
