//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA
    {
        public PLANILLA()
        {
            this.INFORME = new HashSet<INFORME>();
        }
    
        public int ID_PLANILLA { get; set; }
        public string DESCRIPCION { get; set; }
        public int RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<INFORME> INFORME { get; set; }
    }
}
