//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ACTIVIDADES
    {
        public int ID_REGISTRO_ACTIVIDADES { get; set; }
        public int ID_SOLICITUD { get; set; }
        public Nullable<int> RUT_PROFESIONAL { get; set; }
        public int RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
        public virtual SOLICITUDES SOLICITUDES { get; set; }
    }
}
