//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ACCIDENTES
    {
        public REGISTRO_ACCIDENTES()
        {
            this.ALERTA_ACCIDENTE = new HashSet<ALERTA_ACCIDENTE>();
        }
    
        public int ID_REGISTRO_ACCIDENTES { get; set; }
        public string FECHA_ACCIDENTE { get; set; }
        public int ID_DETALLE_ACCIDENTE { get; set; }
    
        public virtual ICollection<ALERTA_ACCIDENTE> ALERTA_ACCIDENTE { get; set; }
        public virtual DETALLE_ACCIDENTE DETALLE_ACCIDENTE { get; set; }
    }
}
