//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        public SERVICIOS()
        {
            this.SERVICIOS_EN_CONTRATOS = new HashSet<SERVICIOS_EN_CONTRATOS>();
        }
    
        public int ID_SERVICIOS { get; set; }
        public string VALOR_SERVICIO { get; set; }
        public System.DateTime FECHA_VIGENCIA { get; set; }
        public System.DateTime FECHA_SERVICIODATE { get; set; }
        public int ID_DETALLES_DOCUMENTOS { get; set; }
    
        public virtual DETALLES_DOCUMENTOS DETALLES_DOCUMENTOS { get; set; }
        public virtual ICollection<SERVICIOS_EN_CONTRATOS> SERVICIOS_EN_CONTRATOS { get; set; }
    }
}
