//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDES
    {
        public SOLICITUDES()
        {
            this.REGISTRO_ACTIVIDADES = new HashSet<REGISTRO_ACTIVIDADES>();
        }
    
        public int ID_SOLICITUD { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public string RESOLUCION { get; set; }
        public int ID_TIPO_SOLICITUDES { get; set; }
        public int RUT_CLIENTE { get; set; }
        public int ID_ESTADO_SOLICITUDES { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_SOLICITUDES ESTADO_SOLICITUDES { get; set; }
        public virtual ICollection<REGISTRO_ACTIVIDADES> REGISTRO_ACTIVIDADES { get; set; }
        public virtual TIPO_SOLICITUDES TIPO_SOLICITUDES { get; set; }
    }
}
