//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SOLICITUDES
    {
        public TIPO_SOLICITUDES()
        {
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
        }
    
        public int ID_TIPO_SOLICITUDES { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
    }
}
