//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomasAccidentes.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PROFESIONAL = new HashSet<PROFESIONAL>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public int ID_ROLES_USUARIOS { get; set; }
        public int ID_ESTADO_USUARIOS { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ESTADO_USUARIOS ESTADO_USUARIOS { get; set; }
        public virtual ICollection<PROFESIONAL> PROFESIONAL { get; set; }
        public virtual ROLES_USUARIOS ROLES_USUARIOS { get; set; }
    }
}
